openapi: 3.0.1
paths:
  /:
    get:
      operationId: getHello
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
components:
  schemas:
    HelloWorld:
      type: object
      properties:
        message:
          type: string
